name: Scheduled update of schema all files

on:
  schedule:
    - cron: '0 2 * * 3' # Runs every Wednesday at 2:00 AM UTC
  workflow_dispatch: # Allow manual trigger as well

jobs:
  update-schema-files-esr-mv2:
    if: ${{ always() }}
    uses: ./.github/workflows/update.yml
    with:
      release: esr
      manifestVersion: 2
    secrets:
      SCHEMA_REPO_DEPLOY_KEY: ${{ secrets.SCHEMA_REPO_DEPLOY_KEY }}

  update-schema-files-esr-mv3:
    if: ${{ always() }}
    needs: update-schema-files-esr-mv2
    uses: ./.github/workflows/update.yml
    with:
      release: esr
      manifestVersion: 3
    secrets:
      SCHEMA_REPO_DEPLOY_KEY: ${{ secrets.SCHEMA_REPO_DEPLOY_KEY }}

  update-schema-files-release-mv2:
    if: ${{ always() }}
    needs: update-schema-files-esr-mv3
    uses: ./.github/workflows/update.yml
    with:
      release: release
      manifestVersion: 2
    secrets:
      SCHEMA_REPO_DEPLOY_KEY: ${{ secrets.SCHEMA_REPO_DEPLOY_KEY }}

  update-schema-files-release-mv3:
    if: ${{ always() }}
    needs: update-schema-files-release-mv2
    uses: ./.github/workflows/update.yml
    with:
      release: release
      manifestVersion: 3
    secrets:
      SCHEMA_REPO_DEPLOY_KEY: ${{ secrets.SCHEMA_REPO_DEPLOY_KEY }}

  update-schema-files-beta-mv2:
    if: ${{ always() }}
    needs: update-schema-files-release-mv3
    uses: ./.github/workflows/update.yml
    with:
      release: beta
      manifestVersion: 2
    secrets:
      SCHEMA_REPO_DEPLOY_KEY: ${{ secrets.SCHEMA_REPO_DEPLOY_KEY }}

  update-schema-files-beta-mv3:
    if: ${{ always() }}
    needs: update-schema-files-beta-mv2
    uses: ./.github/workflows/update.yml
    with:
      release: beta
      manifestVersion: 3
    secrets:
      SCHEMA_REPO_DEPLOY_KEY: ${{ secrets.SCHEMA_REPO_DEPLOY_KEY }}
